### ISSUE TITLE
New file inline input area hidden

### ISSUE THREAD

**Issue by prwhitehead** [equinusocio/material-theme#101]
When creating a new file (note, I have sidebar enhancements installed, so this might not be universal...) the text are partially obscured. Please see attached image: 

![error](https://dl.dropboxusercontent.com/spa/i5l4auj6l0a7fj9/3a8uuu0b.png)

**Comment by ZdravkoEE** [comment]
:+1:  on this. I have the same problem when using the Sublime SFTP/FTP plugin when manually entering path.

**Comment by superguigui** [comment]
I have the same issue (i don't event see the top of the input).
The problem is both present with the native `rename` feature and the various sidebar enhancements functions like `move` `new file` and `new folder`.
The fix for rename would probably apply to the sidebar enhancement issues.

I'm using ST3 Stable Channel, Build 3083 on Yosemite (10.10.3).

Cheers !

**Comment by equinusocio** [comment]
Pls see #67
