### ISSUE TITLE
Markdown syntax highlighting issues after 4.0.1

### ISSUE THREAD

**Issue by kaspersoerensen** [equinusocio/material-theme#1027]
### Summary

After updating to 4.0.1 and not having the old themes longer, my markdown syntax highlighting seems to be off (or maybe I just can't seem to figure out how to config it).

These two screen dumps should describe the issues I am having:

Right margin "overflow":

![skaermbillede 2016-11-04 kl 11 35 00](https://cloud.githubusercontent.com/assets/2018894/20002770/d90af294-a282-11e6-8bff-a6b46785ab50.png)

Incorrects coloring of tags in the XML code
![skaermbillede 2016-11-04 kl 11 35 08](https://cloud.githubusercontent.com/assets/2018894/20002773/dc689090-a282-11e6-9346-495981c75a6e.png)

### Settings (Syntax-specific)
```
{
	"draw_centered": true,
    "draw_indent_guides": false,
    "trim_trailing_white_space_on_save": false,
    "word_wrap": true,
    "wrap_width": 80,
}
```

### Settings
```
{
	"always_show_minimap_viewport": "true",
	"auto_complete_commit_on_tab": "true",
	"bold_folder_labels": "true",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"dictionary": "Packages/Language - English/en_US.dic",
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_bold_tab": "true",
	"material_theme_compact_sidebar": "true",
	"material_theme_small_statusbar": "true",
	"material_theme_small_tab": "true",
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"spell_check": "true",
	"theme": "Material-Theme.sublime-theme"
}
```

### Environment

* Operating system and version:
  * [X] Mac OS 10.11.4
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v 4.0.1

### Side node
IMO - the colors from the old theme looked a lot cleaner than the new ones.

**Comment by equinusocio** [comment]
Can you paste the xml snippet?

**Comment by kaspersoerensen** [comment]
Yes:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Settings>
    <ControlData> </ControlData>
    <CRTData> </CRTData>
    <DICOMData> </DICOMData>
    <CursorData> </CursorData>
    <SportPre> </SportPre>
    <SportPost> </SportPost>
</Settings>
```

**Comment by equinusocio** [comment]
I fixed the markdown raw code background color. The xml issue is caused by the markdown package because it provide two different scopes for the tags, Check this screenshots:

<img width="482" alt="screen shot 2016-11-07 at 18 33 17" src="https://cloud.githubusercontent.com/assets/10454741/20068358/b3a9aebc-a518-11e6-9892-34a68c37c517.png">
<img width="808" alt="screen shot 2016-11-07 at 18 33 24" src="https://cloud.githubusercontent.com/assets/10454741/20068361/b6077158-a518-11e6-92e7-037e6195db24.png">


In this example you can notice that the `<plist>` tag have the right color.
