### ISSUE TITLE
Change color to custom color

### ISSUE THREAD

**Issue by Jones-S** [equinusocio/material-theme#1089]
Hi there. This is no bug and this is no improvement. It's just a simple question.

I am trying to change the comment color a bit, because it is too dark for me. I found that I can change some colors in this file:
```
~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Color\ Highlighter/themes/Material-Theme-Darker.tmTheme
```

I had to edit it outside of Sublime Text, and after saving my file which was open in sublime changed colors. But as soon as I closed the file or when opening another file the colors were back to the default state. How can I permanently change the colors? It seems that it reverts them back immediately, but from what source?

I did not find any Files related to the Material Theme in
```
~/Library/Application\ Support/Sublime\ Text\ 3/Packages/
```
but only in
```
~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
``` 
I found the file `Material Theme.sublime-package`. Which I can't edit at all.

Thanks for sharing some thoughts about how the color schemes work exactly and how to edit some colors.

Cheers and Thanks

J

**Comment by equinusocio** [comment]
Package Control by default download a zipped package that you can't edit.

**METHOD 1**
Install [Package Resource Viewer](https://packagecontrol.io/packages/PackageResourceViewer) to extract the theme and then edit all files. Once you get the extracted folder (inside `Packages`) you will find the `Material-Theme-Darker.tmTheme` inside the  Material Theme folder (under `Packages`).

Please note that until you will have the extracted package you can't view the theme updates since the extracted package have more priority when loaded. If a file is in the extracted folder this file will never get updates/fixes.

**METHOD 2**
Install [Package Resource Viewer](https://packagecontrol.io/packages/PackageResourceViewer), type `resource` in the command palette and choose "Open resource", then find the file you want to edit, edit and save. I don't know if the edit will be permanent, but i think no because you're editing the file directly and next update it will be overwritten.

**Comment by Jones-S** [comment]
Ok thank you very much. I'll try that soon.

**Comment by nshoes** [comment]
I just created my own color scheme based on material-theme and used http://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai. Then just download and replace the .tmTheme file. @equinusocio is right though, on updates this file will be trashed, so be sure to throw it on your GH or in a gist.
