### ISSUE TITLE
Issue with SCSS BEM highlighting class names

### ISSUE THREAD

**Issue by alexmccabe** [equinusocio/material-theme#1137]
### Summary

When using BEM methodology with SCSS, the `Element` and `Modifiers` get highlighted, this is not something I have seen with other colour schemes. 

This does not happen when using regular CSS classnames.

![screenshot 2017-05-30 12 20 32](https://cloud.githubusercontent.com/assets/2529110/26581037/a5a91ffe-4532-11e7-8c64-07b22f6384bc.png)

### Expected behavior

Text should not be highlighted

### Actual behavior

Text is highlighted.

### Steps to reproduce

n/a

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS 10.12.5
  * [ ] Linux ...
* Sublime Text:
  * Build 3126
* Material Theme release:
  * v4.0.6

**Comment by equinusocio** [comment]
This issue is not related to BEM but nested properties that are not allowed in the native CSS syntax. What package do you use for the SCSS syntax (i think [that](https://packagecontrol.io/packages/SCSS))? This is related to your package that doesn't allow nesting. I suggest you to use this package instead for SCSS/SASS. https://packagecontrol.io/packages/Sass
