### ISSUE TITLE
Find and replace, replace missing

### ISSUE THREAD

**Issue by prwhitehead** [equinusocio/material-theme#119]
Hello, i love this theme! There is one thing, which is illustrated in the image below - the find and replace in a folder, or project, is missing the replace text input area. 

![error](https://dl.dropboxusercontent.com/spa/i5l4auj6l0a7fj9/bf_9wqfw.png)

**Comment by limenet** [comment]
I just had a similar issue and in my case (I'm on Windows) I solved it by dragging the invisible divider between code and the find/replace bar up.

![resize-bar](https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif)

(the gif is for illustrative purposes only; the "replace" bar is already visible)

Does this help you?

**Comment by shuriu** [comment]
@prwhitehead I had the same problem as you, used @limenet 's advice. Works! I'm on Yosemite.

**Comment by prwhitehead** [comment]
You learn something new every day :)

**Comment by equinusocio** [comment]
@limenet Thanks for the gif, i will add this stupid issue in the main README file, if someone will read it..

**Comment by limenet** [comment]
@equinusocio You're welcome! I'm sure people have a look at the README since IMO you should read that one first before opening an issue.

Aside from that: I only found your theme due to the [GitHub Explore](https://github.com/trending?since=weekly#pa-material-theme) newsletter where your project was featured (congrats!) and that probably was the reason for the many almost-the-same issues today.

**Comment by equinusocio** [comment]
Thanks :) I've updated the realm file with your gif.

**Comment by animeshsinghweb** [comment]
@limenet Thanks for the rescue. I guess the resizeable dragger is invisible because it is having the same (in this case, black) color, making it indistinguishable.
 
I guess either the default padding for new file function is little less in the theme, or maybe this theme had been made taking Retina screen into more consideration.

However, your solution fixed the issue.

**Comment by DVLP** [comment]
Very bad UX

**Comment by equinusocio** [comment]
@DVLP Very useless comment.

**Comment by DVLP** [comment]
@equinusocio If looking for a basic functionality, previously available without a problem but disappearing after installing this extension requires looking it up in issues of a product then this is indeed very bad UX. Now, What's the point of your comment?

**Comment by equinusocio** [comment]
The point is that you can read all issues like this and you will know that is a sublime bug already reported months ago. And no, there is a easy fix for this.

**Comment by DVLP** [comment]
If it has been reported months ago then it should've been fixed already.

**Comment by enkia** [comment]
@DVLP It's an issue with Sublime itself, not any package that themes the panel. When switching themes, Sublime Text will sometimes retain the height of the previous theme which will cause the bar to appear hidden. The only recourse currently is to resize the panel.

**Comment by arnulfolg** [comment]
Wow, I've been struggling with this a lot; thought it would be about waiting for a theme fix. 'Til now I had been changing themes when I wanted to replace something... 
Thanks for the advice, now my only struggle is solved. Love this theme.

**Comment by ihodev** [comment]
@arnulfolg This bug was fixed in ST 3127+

**Comment by equinusocio** [comment]
@DVLP
