### ISSUE TITLE
Fuzzy title bar text on the dark theme

### ISSUE THREAD

**Issue by lamberttraccard** [equinusocio/material-theme#1190]
The title bar text look fuzzy on the darker themes.

I'm not sure it's very visible on the screen capture.

Seems like there is a text shadow apply but looks odd.

<img width="955" alt="capture d ecran 2017-09-22 a 14 33 12" src="https://user-images.githubusercontent.com/4272598/30744588-047d7956-9fa3-11e7-8007-5ee4cf7bb031.png">

**Comment by equinusocio** [comment]
<img width="242" alt="screen shot 2017-09-23 at 18 55 07" src="https://user-images.githubusercontent.com/10454741/30775281-b59774ba-a090-11e7-948c-3094b8293f09.png">

**Comment by equinusocio** [comment]
@lamberttraccard Consider that Material Theme for sublime text is not under active development cause Sublime Text is now an obsolete software with lack of features compared to other editors.

There is a lot of issue with this software and maintaining this theme is not more affordable. I suggest you to consider other editors like Visual Studio Code + [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)

**Comment by sn0wyfall** [comment]
@equinusocio How come you think that? Wasn't it updated to version 3.0 just 11 days ago?

I've always seen you supporting this theme (and possibly Sublime Text as well). Is there a reason you're irritated at it right now, or was that annoyance building up in you over the last year or so? I'm just curious.

It's quite ironic because I literally switched over to Sublime Text from Atom (with Atom's material theme) because I felt like Atom was outdated, slow, and ugly. These were the things that Sublime Text fixed, which is why I made the switch. It also seemed to me to have more features and be more powerful than Atom. After discovering your material theme, I completely switched over and now I'm here to stay until something better comes along (which is not even close to likely to happen, given how good I think Sublime Text is). That's why I find this comment of yours a bit odd!

**Comment by mallowigi** [comment]
It's easy to understand, he started this project two or more years ago, got excited by including more features and more themes and released a version that worked fine. He closed all his issues, then discovered Visual Studio Code, and started to like it more than Sublime (which I agree as well).

Then suddenly Sublime got updated and some stuff started to break. To him, it's a pain in the ass to take care of something that he is not using actively, still continues to support it for the welfare of the community.

But then people got angry because of bugs, started to curse him for not taking care of his project. He got pissed and became bitter against these people, not against the people that are congrulating the plugin. Still, he doesn't want to use his free time to continue supporting a plugin that he has no more interest in it. He is working on a Visual Studio Code version of it actively, and to him it's much more rewarding than this one.

As an open source project, you are free to take a look at the source code and Sublime Text API and fix the issues, I don't think he will be opposed to that! In fact, that's exactly what I did with the Material Theme for Jetbrains project. The project got abandoned a year ago and stopped working, and the original owner got too busy to take care of it and issues were piling up. I didn't know anything about plugin development for IntelliJ IDEA but I decided to take a look anyway because, well, I had nothing to do at the time and I really wanted it to make it work. Fast forward a year after, I added tons of features to the plugin, got it working for latest releases, and had a lot of fun doing it.

So if you like this project, get your hands dirty and help a developer out.

**Comment by equinusocio** [comment]
@sn0wyfall Sublime Text 3 was in beta release for almost 3 years.. after 3 years of bugfix it come out with no new features (yes it is fast) but the speed is not the only thing you should consider, and remember that you have to buy it for **80$**. 

It doesn't have:
- built-it package manager,
- type checker (Visual Studio IntelliSense is powerful)
- A way to debug extension (it have just the console)
- many other useful features

About the theme engine.. it sucks, it is old and unstable. 

I think **Visual Studio Code** is in the middle between speed and functionalities, the right compromise. It get updates every months (every week if you use the insiders build), is open-source and his community is very large and the dev team follow the community requests. All of this without pay. I asked a lot of features to be added for the theme customisations, and they added them. So i think that a supported text editor, fast (compared to atom, a bit slow compared to ST), free and with a lot o features is better than a commercial software that was in beta for 3 years and come out without 0 features for developers.

**Comment by mallowigi** [comment]
I think Sublime is okay as a text editor++. I use it mostly to open single files, log tickets, and gists/snippets. I would not use it for a project even though I know tons of people that do so.

**Comment by equinusocio** [comment]
@mallowigi I agree with you. Is just a TextEdit replacement now...

**Comment by Fastidious** [comment]
So, there is no fix for this?

**Comment by sn0wyfall** [comment]
@mallowigi I see, you're totally right about that. Thanks for your perspective!

@equinusocio Thank you very much for taking the time to explain. I wholeheartedly agree with what you're saying (and I've considered some of those points before, too!). I'll definitely check Visual Studio out in the future. I'll do my best to provide pull requests to this project, because I won't lie when I say that it changed my life. Thanks a ton for that!

**Comment by aaronsutton** [comment]
I will preface my comment by saying that I'm in no way a developer, and I've never worked with Sublime themes, so please excuse my inelegant workaround.

Using the instructions provided in the readme, I modified the app.json file within the specific theme variant, e.g. darker, and set the color of the title bar to white. Also, I had to manually convert the YAML-tmTheme files with PackageDev to output the color schemes.

```json
  {
    "class": "title_bar",
    "fg": [255, 255, 255], //This is the line I modified
    "bg": [<%= ui.background.primary.rgb %>]
  },
```
This bandaid solution works well enough for me, and can be seen in the image below.
![screen shot](https://user-images.githubusercontent.com/1634530/30949530-f2aeba0a-a3e4-11e7-9d50-e7a86c29d12a.png)

**Comment by equinusocio** [comment]
Since i don’t have this issue (on the same platform), fixing it by changing the color tells me that is a rendering issue with sublime that doesn’t render correctly the aliased font.

**Comment by alexchantastic** [comment]
I started seeing this after I upgraded to MacOS High Sierra (10.13).

![image](https://user-images.githubusercontent.com/604167/31038028-43b1298e-a529-11e7-9e3d-5f9b97c632c3.png)

**Comment by mallowigi** [comment]
Looks like an issue with Sublime rendering. They are applying a gray text-shadow, which is rendering fine on lighter colors, and (very) bad on darker colors. You can open up an issue in the sublime forum https://forum.sublimetext.com/search?q=title%20bar%20order%3Alatest

**Comment by alexchantastic** [comment]
This only seems to happen on the Material darker theme though.

Here is how it looks on Sublime's Adaptive theme:

![image](https://user-images.githubusercontent.com/604167/31100023-d224f7d6-a77c-11e7-92c7-486a8cb4a89d.png)

**Comment by Fastidious** [comment]
Since @equinusocio recommended people to move to Visual Studio Code, I think it is fair to recommend people using Sublime Text, and not willing to give it up (like me) to move to the [Ayu theme](https://github.com/dempfi/ayu). I find it very functional, and more aesthetically beautiful than the Material theme. It is also not broken.

**Comment by sn0wyfall** [comment]
@Fastidious Thanks for the suggestion! I don't think it's necessarily _better_ but they're both good. I'll probably switch between the two.

**Comment by mallowigi** [comment]
@alexchantastic exactly, you can see the shadow even in your screenshot. Since in Darker it is darker than in Adaptive, it doesnt look good. I've played with the colors, and while some colors render well, some don't.

I would submit a bug request, but like Mattia, I don't really care about Sublime and the title is a small issue. At most we can make it white and call it a day.

**Comment by GiancarloGomez** [comment]
Actually I noticed this on several different apps once I upgraded to High Sierra when showing a dark theme. For instance, in my Parallels control center the text looked the same in the dark them view. This might just be a High Sierra issue. On the note to VS Code, it appears to have some crazy stuff happening with High Sierra as well, sometimes the view just stops rendering text and becomes unresponsive. Don't you all just love OS updates :-)

**Comment by tvercruysse** [comment]
sad to see @equinusocio move away from ST3. I have always liked your style. ST3 dev supports ligatures now, that counts for something right ?

**Comment by snwflake** [comment]
Ligatures are still broken as fuck... E.g. `->` with haskell syntax turns into `!!@` ...I mean....what?!?

**Comment by equinusocio** [comment]
Change editor... 🙄

**Comment by sn0wyfall** [comment]
@tvercruysse Wait... do you have more information about this?

**Comment by equinusocio** [comment]
@sn0wyfall by removing the app title bar style you can fix the High CPU issue and this.

**Comment by tvercruysse** [comment]
@snwflake ligatures work fine for me (spoiler i am not a haskell programmer so i just took code from the (visually pleasing) haskell website 
![image](https://user-images.githubusercontent.com/20804569/31773867-5eee5c74-b4e4-11e7-8bab-f0ea88b2d065.png)

**Comment by sn0wyfall** [comment]
@tvercruysse I wonder if it can work with other fonts like [this](https://gist.github.com/renatorib/a0d7af29133c8a775b0740d0b67e32a8)

**Comment by ihodev** [comment]
@sn0wyfall No, that's not possible, but you can use: https://github.com/kiliman/operator-mono-lig

**Comment by sn0wyfall** [comment]
@ihodev Awesome, thank you so much!
