### ISSUE TITLE
Double Click does not fit window to screen

### ISSUE THREAD

**Issue by n1ghtie** [equinusocio/material-theme#1196]
Hi guys,
Love the theme, but after the recent update of sublime text 3 (3143) with Material Theme Active I cannot double click on top of the window to fit my current working window to screen. 

I have mac Sierra latest update. 

When i deactivate theme, the functionality is back and i can double click to fit working window to screen. thats the 'top of the window' I am talking about, not the (red, yellow, green actions)
![screen shot 2017-10-11 at 09 20 51](https://user-images.githubusercontent.com/2650157/31429295-899737e6-ae65-11e7-95b7-9b4b7ece556b.png)

**Comment by mallowigi** [comment]
This is because the Material Theme is theming the title bar, therefore the title bar is becoming part of the UI instead of part of the OS. Other themes, such as Sublime's Adaptive Theme as well, have the same behavior. So it's not a bug.

Currently there is no option to disable title bar theming, so you can't. Maybe I'll add the option if there is enough demand.

**Comment by n1ghtie** [comment]
Thank you!

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme/issues/1189
