### ISSUE TITLE
Please bring back white panels

### ISSUE THREAD

**Issue by mikeroll** [equinusocio/material-theme#219]
Can we please have white panels back as a config option? I really liked the contrast.

Thanks for the great work :)

**Comment by equinusocio** [comment]
Yes, i will do it.

**Comment by thirdsun** [comment]
I agree, those bright panels worked very well with the primary dark colors in an editor. Would appreciate an option to have them back.

**Comment by seanwash** [comment]
As much as I hate +1, etc, I'd really like this too. I actually thought there was a bug happening after my panel colors changed when updated. Thanks!

**Comment by equinusocio** [comment]
Thanks @seanwash. Anyway unfortunately i can't make a settings for this guys. ST allow me to set only one input style for a theme, and i cant change it with a settings because is an external file.

So the only solution is to make another variant of the theme... and this is not a beautiful solution. If someone find a solution on the web let me know, but at the moment we can have the default theme with white panel or dark panel, no settings.

**Comment by chriscandy** [comment]
White panels on dark background makes perfect sense for me. You should bring them back. Keep up the good work!

**Comment by matthewga0** [comment]
So we're talking about the three colors, since we can't add an option to change input style, can we have an option to change the background?

**Comment by equinusocio** [comment]
The panel contain the inputs. So you will have a white panel with a darker input inside (because the find/replace etc panel have a dark inputs). This is the problem. 

The inputs field, contain the background of the input area (image assets) and the input field (where you type) with the style defined in the widget file.  My english isn't so good, i hope you understand.

**Comment by mikefrancis** [comment]
The white panels were my favourite aspect of the theme, such a shame to lose them.

Does anyone know of a fork or alternative which has these back in?

**Comment by matthewga0** [comment]
There will be two families of the theme:

* **Dark & White** dark background with white input style which has the most fans
* **Dark & Dark** dark background with dark input style which is unified

Dark also has two colors so far:

* **Blue Gray**
* **Black**

This will need 4 separate theme packages and 2 color themes.

**Comment by bernardodsanderson** [comment]
I would also love the white panels back. Specially since the autocomplete still has the white panels too.
![style_css](https://cloud.githubusercontent.com/assets/5623786/8331781/b90a4f7e-1a4f-11e5-8764-abda20543c62.png)

**Comment by equinusocio** [comment]
I've made another package (addon) that will enable the white panels and inputs. We have to wait the merge with Package Control. I will add some screenshots in the next days.

https://github.com/equinusocio/material-theme-white-panels

**Comment by equinusocio** [comment]
Search for "Material Theme White Panels" on Package Control ;)

**Comment by mikefrancis** [comment]
White panels are back (yay!) but IMO this doesn't look right:

![screen shot 2015-06-29 at 10 14 58](https://cloud.githubusercontent.com/assets/1672610/8404801/d6da6236-1e47-11e5-8517-abba7d2531ec.png)

Shouldn't the input be the same colour as the panel?

**Comment by equinusocio** [comment]
@mikefrancis Restart Sublime please. :+1:

**Comment by mikefrancis** [comment]
:disappointed: Oops.

**Comment by kentor** [comment]
Eh I'm not a fan of the white menu for autocomplete. How can I get the darker menu back?

**Comment by equinusocio** [comment]
@kentor you see the white autocomplete with the default Material-Theme?

**Comment by kentor** [comment]
Indeed. I updated to the latest version as well.

![screen shot 2015-06-29 at 1 23 29 pm](https://cloud.githubusercontent.com/assets/240493/8417592/6ab04218-1e62-11e5-8f34-c67a32bfc979.png)

**Comment by equinusocio** [comment]
i will fix this, please open a new dedicated issue.
