### ISSUE TITLE
Unable to create new file and folder using the sidebar in Ubuntu 14.04.

### ISSUE THREAD

**Issue by srahulprdxn** [equinusocio/material-theme#358]
Before using the material theme, I could right click on a folder, create a new file and a folder inside the existing folder. Now when I try to do the same, nothing happens.

**Comment by equinusocio** [comment]
@srahulprdxn Please read the README file

**Comment by Revod** [comment]
Hi @equinusocio , i have the same problem, Im using the Material Theme since you created it and i love it and using in my Macbook, on my desktop with windows, but today I installed Elementary OS (Based on Ubuntu 14.04) and i dont see the method of the readme for this, don't see, its a bug on ubuntu or a problem with the theme and sublime?, again thanks for you work with material theme

**Comment by equinusocio** [comment]
This is a bug of sublime text cause by material theme. You can find the fix in the readme file

**Comment by animeshsinghweb** [comment]
I guess if you right click "New File" and then type the name of the file blindly and press enter it would automatically make it. It seems that function is working, but the option is invisible due to low padding of the option maybe because the theme is made by taking retina ready devices into consideration or something like that.

However, if you try resizing an invisible (hover above status bar and mouse would become resizeable at some position) and dragging it up, would make the option visible.

Please See: https://github.com/equinusocio/material-theme/issues/119#issuecomment-112334303

Hope this had helped you @Revod @srahulprdxn :smile: :laughing: :laughing: !

**Comment by srahulprdxn** [comment]
Good one @animeshsinghweb

**Comment by equinusocio** [comment]
Also read the readme file.

**Comment by srahulprdxn** [comment]
@equinusocio Sure.

**Comment by pepps01** [comment]
Where can we find the Readme FIle. All you have been saying is readme .... I have a big problem using it. ANy solutions

**Comment by equinusocio** [comment]
@pepps01 https://github.com/equinusocio/material-theme#known-issues

**Comment by pepps01** [comment]
Thanks ...That helped
