### ISSUE TITLE
Adding a new folder via the sidebar menu

### ISSUE THREAD

**Issue by buildersbrewery** [equinusocio/material-theme#411]
If I right-click a folder in my project via the sidebar and choose to create a `New folder` (subfolder within whatever I clicked), all parts of the bottom popup-menu have the same color including outline, background, text-field text and text-field background as well as label colors. I'm talking about the one that pops up above the statusbar.

**Comment by buildersbrewery** [comment]
Similar issues with `Rename`, although two-toned but messed up.

**Comment by broveloper** [comment]
Also adding a new file causes the same problem.

1. In sidebar, right click a directory
2. Select "New File ..."
3. Can't see the text being typed out at the bottom because font color is same as background.

Love the theme!  Can we get an update for this bug as creating new folders / files are commonly used?

**Comment by equinusocio** [comment]
Simple read the README file :+1:

**Comment by broveloper** [comment]
Thanks, @equinusocio

For anyone reading this later, the README has a link to this bug #67
