### ISSUE TITLE
Theme won't load in ST3 Build 3083 (OSX)

### ISSUE THREAD

**Issue by theqlabs** [equinusocio/material-theme#51]
So currently running ST3 Build 3083, on OS X 10.10.3

Follow instructions on the github page and nothing loads, error as follows: 
![screen shot 2015-06-11 at 9 52 29 am](https://cloud.githubusercontent.com/assets/823183/8108645/ad429f46-101f-11e5-9c57-b78a4f3dd082.png)

I can get the Color Scheme to work by unzipping Color Scheme - Default.sublime-package, and adding the Material Theme .tmTheme files to the ZIP archive, re-compress and restart ST3. At this point the color scheme loads fine (from what I can tell.) 

I can't seem to find a way to get the Theme itself to load, I have tried adding "theme": "Material-Theme.sublime-theme", to the User preferences, I have tried setting an absolute path (/Packages/material-theme/Material-Theme.sublime-theme) etc... to no avail. Currently it looks like this:
![screen shot 2015-06-11 at 9 50 35 am](https://cloud.githubusercontent.com/assets/823183/8108717/26a7d3b0-1020-11e5-8388-5806addde5a4.png)

Please advise.

**Comment by jnmnrd** [comment]
I had that same issue when I tried installing it on ST2...didn't realize I had both ST2/3 installed and was opening 2. But since you're running ST3 try following these instructions, as it was exactly what I did to get it running.

Download the latest version:
https://github.com/equinusocio/material-theme/releases/tag/v0.9.0

Unzip, rename to "material-theme" and place into your packages folder:
![screen shot 2015-06-11 at 10 02 39 am](https://cloud.githubusercontent.com/assets/4108497/8108916/83af797c-1021-11e5-8fe8-c9959638789a.png)

Go to  'preferences' -> 'Settings - User' and paste this in (be sure the directory matches):
{
	"theme": "Material-Theme-Darker.sublime-theme",
	"color_scheme": "Packages/material-theme/schemes/Material-Theme.tmTheme",
}

Restart ST3


Hope that works for you, man

**Comment by theqlabs** [comment]
Being new to ST3 themes, I didn't realize the difference between: 

~/Library/Application\ Support/Sublime\ Text\ 3/Packages/
and
/Applications/Sublime\ Text.app/Contents/MacOS/Packages/

This is a crucial part of making this happen, thanks John works great now!
