### ISSUE TITLE
Syntax color

### ISSUE THREAD

**Issue by appie18** [equinusocio/material-theme#538]
Why was a theme I got used to changed to something else? Is there any way to revert back to the older version? The new syntax coloring annoys me a lot.

**Comment by equinusocio** [comment]
@appie18 You can use the included oceanic next if you don't like the new one.

**Comment by limenet** [comment]
@equinusocio I agree with @appie18 (and Oceanic Next isn't the exact same color scheme as the old one).
My main gripe is the following: I use colors, just like most devs I suppose, a lot - also to spot syntax errors. Thus I rely on my editor's color scheme.
The most recent update (`1.9.7`) to Material Theme (which has [81K installs!](https://packagecontrol.io/packages/Material Theme)) changed the *default* of the biggest visual part of the editor in a [*patch* release](https://github.com/equinusocio/material-theme/releases/tag/v1.9.7) (according to [semver](http://semver.org/)). While I really appreciate all your work you put into this theme (which has been my default pretty much since it got released), I don't think this was a very sensible decision to make such a change.

May I ask you to make the `1.9.1` color scheme the default again and provide the new color scheme as a configurable option?

**Comment by tcauduro** [comment]
Agree with above. Can we get the old theme colour at least as another theme option?  I love this theme, thank you for your work.  But I feel like major colour changes to the default should be added as separate syntax theme altogether or have the old style migrated to a separate named theme.  Is there an easy way I could set this up myself?

**Comment by equinusocio** [comment]
@tcauduro Oks. I will put the new color scheme as alternative (i think it will replace oceanic next)

**Comment by tcauduro** [comment]
Thank you kindly! :)

**Comment by limenet** [comment]
Thanks you! :)

**Comment by equinusocio** [comment]
I think the new color scheme still remain the main one, and the old will become the alternative :+1:

**Comment by chrispassas** [comment]
I was trying to figure out what happened to the colors till I found this issue. Thank you for offering it as an alternative.

**Comment by marcushat** [comment]
Hey, I'm having the same issue.  I use php and changing the color of the variable color from pink to a bull and low contrast blue in the Darker theme pretty much makes it look a like an entirely new theme. Can you please not make huge changes like this to themes. I, like @limenet also use the colors to spot errors and having it suddenly change in an automatic update just completely messes up my workflow. I personally liked the bright variable colors, that's why I chose it over the OceanicNext-Darker variant. If you're going to make this drastic of a change could you please please include it as an additional new theme instead of replacing the existing one. I don't mind it becoming the default, just leave the option to keep what we had before. I don't see any downsides to having more color scheme options and letting the users choose based on their preferences.

Anyways, Thanks a lot for Material, I love everything else about and just switched over to it 5 days ago from itg.flat. 

Before. Notice the contrast. It really helps a lot with coding.
![ice_screenshot_20151209-153807](https://cloud.githubusercontent.com/assets/8149696/11698146/49f5f762-9e8b-11e5-9c06-3a7a225efe53.png)

After the update. Very low contrast. Pretty much a completely new theme. Please let users/fans make decisions like this and don't make it for us. Thanks.
![ice_screenshot_20151209-153943](https://cloud.githubusercontent.com/assets/8149696/11698234/9eb39098-9e8b-11e5-8d52-a908fe446ce2.png)

**Comment by roxguel** [comment]
I agree with @marcushat

**Comment by marcushat** [comment]
Please don't replace Oceanic Next either @equinusocio. There's no need to replace schemes as there may be people that love those schemes. Please just add it as an additional scheme with a new name if it's significantly different.

**Comment by vydn** [comment]
Agree with above. I don't know what's happen after updated, the color look strange and  it's confusing me .

**Comment by equinusocio** [comment]
This changed was discussed here #299. I can't make happy everyone and i don't want to add a to much alternative schemes.. i think this kill exclusivity and balance. Anyway i'm open to PR and helps. Under the holidays i can't give it a lot of time, so it may take some time.

**Comment by bjedrocha** [comment]
I share the same sentiment as most people in this thread and would love to see the old default theme resurrected in some form (as the default again or an alternative). In the meantime, I removed the package from Package Control, installed manually per the instructions in the README, and then modified the `Material-Theme.tmTheme` file directly to use the following

https://github.com/equinusocio/material-theme/blob/4cd04a8c5e89fbb18750565ed7a429e25d0de1cf/schemes/Material-Theme.tmTheme

**Comment by tcauduro** [comment]
If you go to releases you can download the [1.9.1](https://github.com/equinusocio/material-theme/releases/tag/v1.9.1) release, unzip and grab the the Material-Theme.tmTheme file from the schemes folder.  Drop it in your Packages/User folder and update your preferences file to match "color_scheme": "Packages/User/Material-Theme.tmTheme",
Voila.  
I'm a fan of the full interface theme and didn't want to miss out on other updates, so using the User folder as an override works perfectly.  Updates to the rest of the theme will still come through.

**Comment by bjedrocha** [comment]
@tcauduro thanks, that's a lot better than my workaround. Cheers!

**Comment by appie18** [comment]
@tcauduro You are the man! Works like a charm

**Comment by limenet** [comment]
@tcauduro awesome, thank you very much!

**Comment by morkro** [comment]
I also agree with everyone else here. @marcushat made a very good statement.

Don't get me wrong, I really like your theme and appreciate your work but you seriously can't make those major changes just like that. It's an entirely new theme. I do understand the issues mentioned in [#299](https://github.com/equinusocio/material-theme/issues/299) but this isn't a minor bug fix which most users won't even recognise. At least provide an alternative.

**Comment by appie18** [comment]
And the syntax color is changed again. Even using the old menu doesn't bring the old syntax back...

**Comment by equinusocio** [comment]
@appie18 I not made changes to the syntax schemes.

**Comment by chrispassas** [comment]
I have the most up to date version and the OLD SYNTAX is still available and working for me.

**Comment by equinusocio** [comment]
@chrispassas you have 3102/3103 ?

**Comment by chrispassas** [comment]
@equinusocio I have Sublime 3102 and I ran Package Manager Upgrade and have the latest published version of the Materials Theme.

I still have the OLD color schemes available and working. I've been using it all day.

**Comment by appie18** [comment]
@equinusocio I have 3101, my editor updated and the syntax just got messed up again.

**Comment by chrispassas** [comment]
After some Sublime updates I have had to reselect my color scheme but its been fine. I assume something in the sublime update triggers it to switch back to the default color scheme. Normally Sublime updates haven't interfered with my preferences until very recently.

**Comment by marcushat** [comment]
Ditto. Still working for me too

**Comment by equinusocio** [comment]
There is some common issues with Package Control. Sometimes breaks the package when updating.

**Comment by appie18** [comment]
@equinusocio Do you think there is a solution?

**Comment by equinusocio** [comment]
I don't know :(
