### ISSUE TITLE
Package is removed from Package Control?

### ISSUE THREAD

**Issue by NoNameProvided** [equinusocio/material-theme#574]
https://packagecontrol.io/packages/Material%20Theme

![img](https://cloud.githubusercontent.com/assets/4706265/12085511/1baca1cc-b2c1-11e5-9f69-c5e4855de405.png)

**Comment by equinusocio** [comment]
mmm i will check. thank you.

**Comment by manoverda** [comment]
Package control json file is empty. All packages are removed. The issue comes from package control and not from each packages.
See this [defect](https://github.com/wbond/package_control/issues/1057) for more information.
You can check the [json](https://packagecontrol.io/channel_v3.json) to see that no packages are available anymore.

**Comment by equinusocio** [comment]
thanks. we have to wait

**Comment by manoverda** [comment]
Resolved :)
You can check the [Material Theme Package Control](https://packagecontrol.io/packages/Material%20Theme) website
