### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by urec** [equinusocio/material-theme#629]
Hi, great theme, thank you! 
Have a question) when the design changed code folding icon(seeming)?
![1](https://cloud.githubusercontent.com/assets/12876772/12659529/4ef7f6b8-c620-11e5-88da-56014152fffe.jpg)

**Comment by equinusocio** [comment]
You have to do this manually since ST fix the bug. Do to this, install [Extract Sublime Package](https://packagecontrol.io/packages/Extract%20Sublime%20Package), extract Default theme and then put inside the extracted folder (Inside packages directory) your `fold.png` images. I use this:

![fold](https://cloud.githubusercontent.com/assets/10454741/12848317/6ba86bfe-cc19-11e5-98ae-7cf1345e65e7.png)
![fold 2x](https://cloud.githubusercontent.com/assets/10454741/12848318/6ba8ecc8-cc19-11e5-9c3a-5e7aefd0d411.png)

**Comment by urec** [comment]
Thank you!
