### ISSUE TITLE
can't see the bottom text input

### ISSUE THREAD

**Issue by cameronjroe** [equinusocio/material-theme#67]
![screen shot 2015-06-12 at 8 49 20 pm](https://cloud.githubusercontent.com/assets/1614348/8142242/a8c65a36-1144-11e5-8811-167988164fd4.png)

**Comment by gj1118** [comment]
see #18

**Comment by cameronjroe** [comment]
I saw that. It works with `cmd+F` but breaks when using [SideBarEnhancements](https://github.com/titoBouzout/SideBarEnhancements) Any ideas?

**Comment by equinusocio** [comment]
i use  sidebar enhancement  and i have no problema with renane/nove/duplicate ecc. You tried panel resize?

**Comment by pratyushpundir** [comment]
![screen shot 2015-06-13 at 1 57 59 pm](https://cloud.githubusercontent.com/assets/1782464/8143617/3f4b1f20-11d4-11e5-94cc-20f9936d9a94.png)
Facing the same issue with SideBar enhancements but works ok with default sublime actions!

**Comment by equinusocio** [comment]
Resize the panel by dragging the top edge...

**Comment by cameronjroe** [comment]
Thanks, didn't see that.

**Comment by augbog** [comment]
For visual reference, this is what you should be seeing after you have expanded the top edge. It's hard to see the top-edge because there is no border color. Thought I'd post this in case people were confused.

![screen shot 2015-06-15 at 1 43 59 pm](https://cloud.githubusercontent.com/assets/2054339/8170319/c47e8100-1364-11e5-9890-56ebc352a380.png)

**Comment by pratyushpundir** [comment]
Agreed. Faced the same issue. Couldn't see the panel border so had a hard time finding it so I could grab and resize it. 



--
Best Regards

Pratyush Pundir

Email : pratyushpundir@icloud.com
Other email : pratyush.sublimearts@gmail.com
Mobile : +91 78380 79456
Facebook : http://www.facebook.com/PratyushPundir
Twitter : http://www.twitter.com/PratyushPundir
Skype : pratyushpundir

**Comment by huglester** [comment]
@equinusocio any update on this?

**Comment by equinusocio** [comment]
No. This is not a theme bug.

**Comment by kaaaahhhhnnnn** [comment]
How do you justify saying it's not a theme bug when (AFAIK) only this theme is effected?  I've never seen this with any other theme so even if it's a bug in ST there is something unique to the theme that's triggering it.

**Comment by equinusocio** [comment]
@kaaaahhhhnnnn because this theme use a larger padding for the panel . Other themes use a standard padding so Sublime Text doesn't have to recalculate the default panel size and position. I saw this happen with a lot of other themes in 3 years. This is not a theme bug that i can fix, and isn't a "fatal" bug, just read the README file.
