### ISSUE TITLE
Please use regular install procedures through package manager

### ISSUE THREAD

**Issue by specialorange** [equinusocio/material-theme#7]

**Comment by auginator** [comment]
+1 -> https://packagecontrol.io/docs/submitting_a_package

**Comment by mattborn** [comment]
As warned, I think a developer died…

![:sadface:](https://dl.dropboxusercontent.com/s/cwzyr4wn8rdb03s/2015-06-03%20at%2012.03%20PM.png)

**Comment by HendrikPetertje** [comment]
I think he knows how the process of submitting a package works since his other themes are on package controll. Please note that this theme might still be under alpha development... he started working on it a few days ago and as of now there is no production-ready master branch.

give the good man some time ;)

**Comment by Revod** [comment]
@HendrikPetertje yeah, is a beta theme, There are many errors to fix, and which must be given time,he is working but the advance is excellent, love the theme of @equinusocio

**Comment by equinusocio** [comment]
Thanks guys. I will put the theme on package control when is stable because i don't want to bore developers with ui glitch, frenquent updates and no syntax color defined. Be patient :)
