### ISSUE TITLE
Italic option for comments?

### ISSUE THREAD

**Issue by jacine** [equinusocio/material-theme#710]
First, thank you so much for this theme.  It's beautifully done.

I was wondering if you could possibly provide an option/setting to make comments display in italics. I'm not sure how easy or hard this would be to implement, but figured it was worth asking. I'm using the new Operator Mono font, and really missing the awesome italic version it provides.  You can see it in action here: http://blog.codepen.io/2016/02/18/new-typeface-operator/

Thanks for considering! :)

**Comment by saadq** [comment]
Until equinusocio replies, it actually wouldn't be too hard to do this yourself. Just follow these steps:

1. Install `PackageResourceViewer` from Package Control.
2. Open up the command palette with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>. If you're on Mac, use <kbd>⌘</kbd> instead of <kbd>Ctrl</kbd>.
3. Type `PackageResourceViewer: Open Resource` and press <kbd>Enter</kbd>
4. Type `Material Theme` and press <kbd>Enter</kbd>
5. Type `schemes/` and press <kbd>Enter</kbd>
6. Using the arrow keys, choose the color scheme you want to change and press <kbd>Enter</kbd>
7. Scroll down through the file until you see a block like this:

```
<dict>
  <key>name</key>
  <string>Comments</string>
  <key>scope</key>
  <string>comment, punctuation.definition.comment, text.cancelled, meta.punctuation.separator, markup.strikethrough</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#546E7A</string>
  </dict>
</dict>
```

You can also just use <kbd>Ctrl</kbd>+<kbd>F</kbd> to find `Comments`

8. Underneath the foreground and hex color setting, add a `fontStyle` key and a string of `italic`. The end result in that block of code would look like this:

```
<dict>
  <key>name</key>
  <string>Comments</string>
  <key>scope</key>
  <string>comment, punctuation.definition.comment, text.cancelled, meta.punctuation.separator, markup.strikethrough</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#546E7A</string>
    <key>fontStyle</key>
    <string>italic</string>
  </dict>
</dict>
```

and you're done! :)

**Comment by michelecos** [comment]
You can also make your changes permanent so that a theme update will incorporate them, look at this thread

https://github.com/equinusocio/material-theme/issues/254#issuecomment-120721902

**Comment by saadq** [comment]
I've also updated my answer to account for theme updates, but sweet thanks for posting that!

**Comment by jacine** [comment]
Thank you so much @saadq & @michelecos! 

This works beautifully. A setting would be easier, and ultimately I'd rather not hack the theme, so hopefully this will still be considered, but I'm so grateful that you both took the time to write out such clear instructions on how to override this. 

Thanks again!  :smile:

**Comment by equinusocio** [comment]
@jacine unfortunately sublime text doesn't allow settings for the color scheme. Settings are allowed only for the ui theme. So, at the moment, you have to do it manually in your local installation.

**Comment by jacine** [comment]
Ahh, ok.  Thank you @equinusocio!

**Comment by equinusocio** [comment]
@jacine Added in the next release

**Comment by jacine** [comment]
That's awesome!  Thank you so much @equinusocio!

**Comment by equinusocio** [comment]
All comments will be Italic with no options to change it.

**Comment by saadq** [comment]
So are you including a separate color scheme file for each theme now or are you basically changing the existing color schemes to use italics for comments?

**Comment by equinusocio** [comment]
I've changed the existing schemes.
