### ISSUE TITLE
Last update broke Syntax Highlighting for Sass

### ISSUE THREAD

**Issue by ivancuric** [equinusocio/material-theme#783]
I prefer using https://github.com/P233/Syntax-highlighting-for-Sass over https://github.com/nathos/sass-textmate-bundle.

Since the last update the classes, pseudoelements, pseudoselectors and other features broke. The classes are just plain text, and pseudoitems are solid red. IDs and element selectors work fine.

**Comment by equinusocio** [comment]
I can't support every third-party packages. Sublime Text become with a build-in sass package (textmate-bundle) that work perfectly. I can't help, i'm sorry.

**Comment by ivancuric** [comment]
Wouldn't agree that it works perfectly since it doesn't recognize a ton of properties like `pointer-events`, browser specific prefixer, or even the `main` element. Not to mention that it doesn't have the basic snippets for sass mixins and functions.

But that's beside the point. I'm pretty sure that it's a bug introduced in https://github.com/equinusocio/material-theme/commit/13d9a073bcb35730b15bf702a1fcbd9744f804bb since the OceanicNext ones still work fine.

**Comment by equinusocio** [comment]
`Syntax-highlighting-for-Sass Latest commit 6556daa  on Aug 12, 2014` and doesn't fully support the new Sublime Text syntax system. When 3.0 branch will be released on Package Control i will consider to add the support for it, but since every package provides differents syntax scopes i can support only one package, the most recent one.
