### ISSUE TITLE
Daily restart of Sublime required

### ISSUE THREAD

**Issue by g105b** [equinusocio/material-theme#785]
The theme is updated very often, which I hold a lot of admiration for. However, each time there is a release, the theme breaks and I have to restart Sublime. This is a daily occurrence.

See attached screenshot. This is what it looks like after the theme breaks.

![image](https://cloud.githubusercontent.com/assets/358014/14956856/cb419ee2-1079-11e6-9809-c0f9b3513335.png)

Once I restart Sublime, I have to then open the user settings and re-type `"theme": "Material-Theme-Darker.sublime-theme",`. After this has saved, I have to restart Sublime again. Happening every day, this has become very tedious.

I understand that this is probably a Sublime limitation rather than a Material Theme issue, but after getting my colleagues to install Material Theme, it's embarrassing that my suggestion has now broken their text editors every morning.

Is there a way around this?

**Comment by equinusocio** [comment]
Each update you have to wait until package control finish to update all packages, the theme will be reactivated. If you use ST 3110 you don't see any UI glitch after the update.

Otherwise you can just disable autoupdate through Package Control palette. 

Please before open a new issue search for a similar one. 👍
