### ISSUE TITLE
Material Theme hangs Sublime Text when starting with existing project

### ISSUE THREAD

**Issue by evenfrost** [equinusocio/material-theme#924]
### Summary

When starting Sublime Text with existing project Material Theme hangs the app. The only way to overcome it is to press 'Ctrl+Shift+P' (Command Pallete is not shown either but it's functional), type 'Close Project' (or just 'CP') and press Enter. Again, these steps have to be performed on completely frozen ST's interface. After that I close and reopen ST, and the theme is reset to Default. There is no issues with default one, this only happens when using Material. Tested on both home and work computer, using Ubuntu 15.10 and 16.04.  
#891 is possibly related. 

### Expected behavior

Material theme won't freeze ST interface. 

### Actual behavior

Material theme freezes ST interface.

### Steps to reproduce

1. Load ST with Material theme on and into existing project.

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [ ] Mac OS ...
  * [x] Linux Ubuntu 16.04.1 with Gnome 3.18
* Sublime Text:
  * Build 3...
* Material Theme release:
  * v3.0.2

**Comment by equinusocio** [comment]
I do every time i don't have any issue like this. I will close because the theme cannot freeze the app. Probably you have other packages that crash/freeze at startup. I can suggest you to purge material theme, remove all other themes and reinstall it through PC. Note that the v3.1.0 will be available in 1 hr.
