### ISSUE TITLE
Spinner indicator still not showing

### ISSUE THREAD

**Issue by bonilladisseny** [equinusocio/material-theme#950]
I've opened an issue like 9 days ago [#933](https://github.com/equinusocio/material-theme/issues/933) and is marked as closed, but as I commented in that thread it seems that the issue is not solved.

Perhaps the spinner icon does not exist?

**Comment by bonilladisseny** [comment]
I guess this issue has no priority, but it would be nice if it worked

**Comment by equinusocio** [comment]
Hi can't figure out how to fix this, the code is correct and i don't know what happen.

**Comment by marcofugaro** [comment]
I think this is your issue man

https://github.com/equinusocio/material-theme/blob/develop/.src/themes/default/sidebar.json#L242

Setting opacity to 1 fixes it.
Also works by explicitly declaring the opacity on your accent color layers (also I don't know why you used `layer1` instead of `layer0`).

On a side note: testing it, I noticed that on your theme as well, since the last update, the spinner doesn't work on folders, and it appears as just a white box, does this happen to you also?

**Comment by equinusocio** [comment]
@marcofugaro Thanks! I will investigate.

**Comment by bonilladisseny** [comment]
Now it works, perfect! Good to see this working. Thanks!
